<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_guest_arrival_tests.TestHotelReservation-20240424224423" tests="59" file="test_guest_arrival_tests.py" time="0.142" timestamp="2024-04-24T22:44:24" failures="1" errors="58" skipped="0">
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_get_reservation_data_manipulated_tests" time="0.005" timestamp="2024-04-24T22:44:23">
		<failure type="AssertionError" message="&quot;'HotelManager' object has no attribute 'load_json'&quot; != 'Error: reservation has been manipulated'
- 'HotelManager' object has no attribute 'load_json'
+ Error: reservation has been manipulated
"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/venv/lib/python3.10/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 180, in test_get_reservation_data_manipulated_tests
    self.assertEqual(exception_message, "Error: reservation has been manipulated")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: "'HotelManager' object has no attribute 'load_json'" != 'Error: reservation has been manipulated'
- 'HotelManager' object has no attribute 'load_json'
+ Error: reservation has been manipulated

]]></failure>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_case_valid_reservation_invalid_arrival_date" time="0.005" timestamp="2024-04-24T22:44:23">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/venv/lib/python3.10/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 74, in test_case_valid_reservation_invalid_arrival_date
    mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 1VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 102, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 2INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 4INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 5INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 15INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 16INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 19INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 20INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 21INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 22INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 23INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 24INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 25INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 26INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 29INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 30INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 31INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 32INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 33INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 34INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 37INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 38INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 39INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 40INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 41INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 42INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 43INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 44INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 45INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 47INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 48INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 50INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 51INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 52INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 53INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 54INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 55INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 57INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 58INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 59INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 61INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 62INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 63INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 64INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 67INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 70INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 71INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 72INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 73INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 74INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 75INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 76INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 77INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 78INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 79INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 80INVALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 81INVALID]" time="0.133" timestamp="2024-04-24T22:44:24">
		<error type="AttributeError" message="'HotelManager' object has no attribute 'load_json'"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 123, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 123, in guest_arrival
    my_id_card, my_localizer = self.validate_data_guest_arr(file_input)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 141, in validate_data_guest_arr
    input_list = self.load_json(file_input, "Error: file input not found")
AttributeError: 'HotelManager' object has no attribute 'load_json'
]]></error>
	</testcase>
</testsuite>
