<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_room_reservation_tests.TestHotelReservation-20240418140040" tests="6" file="test_room_reservation_tests.py" time="0.069" timestamp="2024-04-18T14:00:40" failures="4" errors="0" skipped="0">
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_duplicated_id_reservation_tests" time="0.001" timestamp="2024-04-18T14:00:40"/>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_duplicated_reservation_tests" time="0.002" timestamp="2024-04-18T14:00:40"/>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC1VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<failure type="AssertionError" message="'450a53be9b39944e62e7164ca5f5aadf' != '8c4e5eab4246f428fbf293cfa669bb30'
- 450a53be9b39944e62e7164ca5f5aadf
+ 8c4e5eab4246f428fbf293cfa669bb30
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 499, in subTest
    yield
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 170, in test_parametrized_cases_tests
    self.assertEqual(result, valor)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '450a53be9b39944e62e7164ca5f5aadf' != '8c4e5eab4246f428fbf293cfa669bb30'
- 450a53be9b39944e62e7164ca5f5aadf
+ 8c4e5eab4246f428fbf293cfa669bb30

]]></failure>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC2VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<failure type="AssertionError" message="'74a961610a0f1c048976007358ba7155' != 'c3ebc521579051f58c2aaaf48ec42cbf'
- 74a961610a0f1c048976007358ba7155
+ c3ebc521579051f58c2aaaf48ec42cbf
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 499, in subTest
    yield
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 170, in test_parametrized_cases_tests
    self.assertEqual(result, valor)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '74a961610a0f1c048976007358ba7155' != 'c3ebc521579051f58c2aaaf48ec42cbf'
- 74a961610a0f1c048976007358ba7155
+ c3ebc521579051f58c2aaaf48ec42cbf

]]></failure>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC3VALID]" time="0.000" timestamp="0001-01-01T00:00:00">
		<failure type="AssertionError" message="'846940dc519dfeabf68522ff4e71ae8e' != 'b3694e0bb5f1cd945f788b8e147678a0'
- 846940dc519dfeabf68522ff4e71ae8e
+ b3694e0bb5f1cd945f788b8e147678a0
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 499, in subTest
    yield
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 170, in test_parametrized_cases_tests
    self.assertEqual(result, valor)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '846940dc519dfeabf68522ff4e71ae8e' != 'b3694e0bb5f1cd945f788b8e147678a0'
- 846940dc519dfeabf68522ff4e71ae8e
+ b3694e0bb5f1cd945f788b8e147678a0

]]></failure>
	</testcase>
	<testcase classname="test_room_reservation_tests.TestHotelReservation" name="test_parametrized_cases_tests [TC4VALID]" time="0.066" timestamp="2024-04-18T14:00:40">
		<failure type="AssertionError" message="'2e6701dd0b065faa56d7199d878d928e' != '5bab7c1d92042ed058e2d486c872614a'
- 2e6701dd0b065faa56d7199d878d928e
+ 5bab7c1d92042ed058e2d486c872614a
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 499, in subTest
    yield
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_room_reservation_tests.py", line 170, in test_parametrized_cases_tests
    self.assertEqual(result, valor)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '2e6701dd0b065faa56d7199d878d928e' != '5bab7c1d92042ed058e2d486c872614a'
- 2e6701dd0b065faa56d7199d878d928e
+ 5bab7c1d92042ed058e2d486c872614a

]]></failure>
	</testcase>
</testsuite>
