<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_guest_arrival_tests.TestHotelReservation-20240426191605" tests="3" file="test_guest_arrival_tests.py" time="0.137" timestamp="2024-04-26T19:16:05" failures="0" errors="1" skipped="0">
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_case_valid_reservation_invalid_arrival_date" time="0.005" timestamp="2024-04-26T19:16:05"/>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_get_reservation_data_manipulated_tests" time="0.006" timestamp="2024-04-26T19:16:05"/>
	<testcase classname="test_guest_arrival_tests.TestHotelReservation" name="test_parametrized_cases_tests [RF2 1VALID]" time="0.126" timestamp="2024-04-26T19:16:05">
		<error type="HotelManagementException" message="ckeckin  ya realizado"><![CDATA[Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 498, in subTest
    yield
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_guest_arrival_tests.py", line 102, in test_parametrized_cases_tests
    valor = mngr.guest_arrival(test_file)
  File "/Users/ellaz-j/PycharmProjects/G88.2024.T06.EG3/src/main/python/uc3m_travel/hotel_manager.py", line 52, in guest_arrival
    raise HotelManagementException("ckeckin  ya realizado")
uc3m_travel.hotel_management_exception.HotelManagementException: ckeckin  ya realizado
]]></error>
	</testcase>
</testsuite>
