<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_checkout_tests.TestDeliverProduct-20240418140040" tests="7" file="test_checkout_tests.py" time="0.032" timestamp="2024-04-18T14:00:40" failures="7" errors="0" skipped="0">
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_already_checkout" time="0.014" timestamp="2024-04-18T14:00:40">
		<failure type="AssertionError" message="'8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/.venv/lib/python3.9/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 45, in setUp
    self.assertEqual(localizer, "450a53be9b39944e62e7164ca5f5aadf")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf

]]></failure>
	</testcase>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_checkin_code_not_found_date_signature" time="0.003" timestamp="2024-04-18T14:00:40">
		<failure type="AssertionError" message="'8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/.venv/lib/python3.9/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 45, in setUp
    self.assertEqual(localizer, "450a53be9b39944e62e7164ca5f5aadf")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf

]]></failure>
	</testcase>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_checkout_ok" time="0.004" timestamp="2024-04-18T14:00:40">
		<failure type="AssertionError" message="'8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/.venv/lib/python3.9/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 45, in setUp
    self.assertEqual(localizer, "450a53be9b39944e62e7164ca5f5aadf")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf

]]></failure>
	</testcase>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_bad_date_signature" time="0.003" timestamp="2024-04-18T14:00:40">
		<failure type="AssertionError" message="'8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/.venv/lib/python3.9/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 45, in setUp
    self.assertEqual(localizer, "450a53be9b39944e62e7164ca5f5aadf")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf

]]></failure>
	</testcase>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_no_date" time="0.003" timestamp="2024-04-18T14:00:40">
		<failure type="AssertionError" message="'8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/.venv/lib/python3.9/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 45, in setUp
    self.assertEqual(localizer, "450a53be9b39944e62e7164ca5f5aadf")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf

]]></failure>
	</testcase>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_no_store_check_in" time="0.003" timestamp="2024-04-18T14:00:40">
		<failure type="AssertionError" message="'8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/.venv/lib/python3.9/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 45, in setUp
    self.assertEqual(localizer, "450a53be9b39944e62e7164ca5f5aadf")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf

]]></failure>
	</testcase>
	<testcase classname="test_checkout_tests.TestDeliverProduct" name="test_guest_checkout_store_check_in_is_empty" time="0.003" timestamp="2024-04-18T14:00:40">
		<failure type="AssertionError" message="'8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf
"><![CDATA[Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/.venv/lib/python3.9/site-packages/freezegun/api.py", line 827, in wrapper
    result = func(*args, **kwargs)
  File "/Users/a19787/PycharmProjects/G88.2024.T06.EG3/src/unittest/python/test_checkout_tests.py", line 45, in setUp
    self.assertEqual(localizer, "450a53be9b39944e62e7164ca5f5aadf")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 1211, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '8c4e5eab4246f428fbf293cfa669bb30' != '450a53be9b39944e62e7164ca5f5aadf'
- 8c4e5eab4246f428fbf293cfa669bb30
+ 450a53be9b39944e62e7164ca5f5aadf

]]></failure>
	</testcase>
</testsuite>
